version: '3'

services:

  devchapcicd:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
     - "80:4000"
    stdin_open: true
    tty: true
    volumes:
     - ./../repos:/devchapcicd
